Added lsblk and blkid for issue #113
rackerlabs/configsnap pull request #115
Opened 2020-08-15 08:22 UTC by JoeyPetersen

Here are the proposed additions.

2020-08-15 11:17 UTC, rhodesn requested changes
Thanks for the PR - left a couple minor comments.

2020-08-15 11:17 UTC, nrhodes91 commented on configsnap
> +if os.path.exists('/usr/bin/lsblk')
Missing a `:` on the end of here.

2020-08-15 11:17 UTC, nrhodes91 commented on configsnap
> +if os.path.exists('/usr/bin/blkid')
Missing `:`.

2020-08-16 10:30 UTC, JoeyPetersen commented on configsnap
> +if os.path.exists('/usr/bin/lsblk')
I amended my commit and fixed this.

2020-08-16 10:30 UTC, JoeyPetersen commented on configsnap
> +if os.path.exists('/usr/bin/blkid')
I amended my commit and fixed this.

2020-08-16 10:32 UTC, merged

2020-08-16 10:32 UTC, nrhodes91 commented
Thanks!