updating README.md file with newly added --config option
rackerlabs/configsnap pull request #97
Opened 2018-11-01 15:43 UTC by popindavibe

Just updating the Readme file from the output of `-h` option.

2018-11-02 06:01 UTC, rhodesn requested changes
I popped a couple of suggestions in just to make it clear that the additional.conf file is read by default whether specified on the command line or not.

2018-11-02 06:01 UTC, rhodesn commented on README.md
> +with PHASE containing "post" or "rollback". An optional file,
```suggestion
with PHASE containing "post" or "rollback". A default config file,
```

2018-11-02 06:01 UTC, rhodesn commented on README.md
> +/etc/configsnap/additional.conf, can be provided for extra files, directories
```suggestion
/etc/configsnap/additional.conf, can be customised to include extra files, directories
```

2018-11-02 06:01 UTC, rhodesn commented on README.md
> +                        overwrite default.
```suggestion
                        override default.
```

2018-12-02 13:36 UTC, popindavibe commented
All suggestions approved, ready for review/merge.

2018-12-02 14:15 UTC, rhodesn approved these changes

2018-12-02 14:15 UTC, nrhodes91 commented
Awesome, thanks for reviewing Jean.

2018-12-02 14:15 UTC, merged